name: 🚀 Feature request
description: Suggest a feature that will improve unlazy
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request!

        Please check that there is not an existing issue covering the scope of the feature you have in mind.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you think would be a helpful addition to unlazy, including the possible use cases and alternatives you have considered.
      placeholder: Feature description
    validations:
      required: true
  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional information
      description: Additional information that helps me decide how to proceed.
      options:
        - label: Would you be willing to help implement this feature?
        - label: Can you think of other implementations of this feature?
  - type: checkboxes
    id: required-info
    attributes:
      label: Final checks
      description: Before submitting, please make sure you do the following
      options:
        - label: Check existing [issues](https://github.com/johannschopplich/unlazy/issues).
          required: true
